---
- hosts: 172.31.22.2
  become: yes
  tasks:
  - name: i want to download remote file
    get_url:
     url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
     dest: /home/suresh/jenkins.war
     force_basic_auth: yes
     
