---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git on ubuntu node
    apt:
     name: git
     state: present

  - name: i want to install tree
    apt:
     name: tree
     state: present    