---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to uninstall webserver on ansible ubuntu nodes
    apt:
     name: apache2
     state: absent

  - name: i want to uninstall webserver on ansible redhat nodes
    yum:
     name: httpd
     state: absent  