---
- name: download tar file, that you copied from the tomcat website
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz
    dest: /home/suresh/apache-tomcat-8.5.5.tar.gz
    force_basic_auth: yes

- name: create the directory, to install tomcat to the /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory

- name: Extract tar file into /opt/tomcat directory
  command:
    cmd: tar xzvf /home/suresh/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE
